# Node.js Piepeline
# Build a Node.js project.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    displayName: 'npm install'
    inputs:
      verbose: false

  - task: Npm@1
    displayName: 'npm run build-prod'
    inputs:
      command: custom
      verbose: false
      customCommand: 'run ng build api --prod'

  - task: CopyFiles@2
    displayName: 'Copy node modules to: dist/apps/api'
    inputs:
      Contents: 'node_modules/**'
      TargetFolder: dist/apps/api

  - task: ArchiveFiles@2
    displayName: 'Archive files'
    inputs:
      rootFolderOrFile: dist/apps/api
      includeRootFolder: false

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: drop'
